# Generated by Django 5.1.4 on 2024-12-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_herosection_image_herosection_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Feature Title', max_length=255)),
                ('description', models.TextField(default='Feature description.')),
                ('icon_svg', models.TextField(default='', help_text='Paste SVG content here for the icon')),
                ('link_text', models.CharField(default='Learn more', max_length=100)),
                ('link_url', models.URLField(default='#', max_length=500)),
            ],
        ),
    ]
