# Generated by Django 5.1.4 on 2024-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sign up for our newsletter', max_length=255)),
                ('description', models.TextField(default='Stay up to date with our latest announcements, exclusive discounts, and upcoming events. Sign up now!')),
                ('terms_of_service_url', models.URLField(default='#', max_length=500)),
                ('privacy_policy_url', models.URLField(default='#', max_length=500)),
            ],
        ),
    ]
