# Generated by Django 5.1.4 on 2024-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('svg_icon', models.TextField(default='', help_text='Paste SVG content here for the icon')),
                ('message', models.CharField(help_text='The banner message to display.', max_length=255)),
                ('link_text', models.CharField(blank=True, help_text='Text for the link.', max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL for the link.', max_length=500, null=True)),
            ],
        ),
    ]
